name: bmi_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  json_annotation: ^4.6.1
  shared_preferences: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/ic_launcher.png
